# This starter workflow is for a CMake project running on a single platform
name: Checkout, build then run production code when push or merge to "release" branch

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  # Customize the CMake build type here
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Configure CMake
        run: ./configure_production.sh

      - name: Build
        # Build your program with the given configuration
        run: ./build_production.sh

      - name: Test
        working-directory: ${{github.workspace}}
        # Execute tests defined by the CMake configuration.
        run: ./run_production.sh

