# This starter workflow is for a CMake project running on a single platform
name: Checkout, build then test the code when push or merge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here
  BUILD_TYPE: Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Configure CMake
      run: ./configure_test.sh

    - name: Build
      # Build your program with the given configuration
      run: ./build_test.sh

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest --verbose

